apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: vault-provider
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/upbound/provider-vault:v1.0.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
---
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
spec:
  address: http://vault.vault-system:8200
  credentials:
    secretRef:
      key: credentials
      name: vault-provider-secret
      namespace: crossplane-system
    source: Secret
