apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: vault-provider
  namespace: crossplane-system
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/upbound/provider-vault:v1.0.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
---
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
  namespace: crossplane-system
spec:
  address: vault.vault-system
  credentials:
    secretRef:
      key: token
      name: vault-provider-secret
      namespace: crossplane-system
    source: Secret
